### ISSUE TITLE
add target for badge button

### ISSUE THREAD

**Issue by scubax07** [kiwisip/BadgeControl#2]
Hi, how can I add target function for the badge when I click on it?
And thanks for this awesome library.

**Comment by rkrenecky** [comment]
Hi! Thanks for your feedback.
Unfortunately any interaction with the badge is not currently supported as there is no way to access the badge's view. What is your use case? Would making `currentBadge` property on `BadgeController` public instead of private solve your issue?

**Comment by scubax07** [comment]
Hi, again. Thanks for your response. I am making an MCQ app in which the badge button shows the number of answers selected, and also be submitted when the badge is clicked. I will let you know if I come up with a better solution or suggestions.

**Comment by rkrenecky** [comment]
Hi! 

I just released new version of BadgeControl that contains changes that should solve your problems. You can now use `currentBadge` property on `BadgeController` to access the current badge (and you can for example attach a gesture recognizer to it so that you can click on it).

Also you can create your own `BadgeImageView` as the initializer is now public (unfortunately it's not possible to modify it after creation, if you need this behavior, feel free to open a PR!).

Let me know if this solves your issue!
